### ISSUE TITLE
rename some items

### ISSUE THREAD

**Issue by jurasikasan** [GiannisAnasta/Companies#21]
original:

> > rename "Details(+)" to "Details" or "comments" etc (in Eng localisation)
> > rename "Name" to "Company name"
> > rename button "Add" to "Add new company"
> > rename "Upload" to "Upload new file" etc

rename "Details(+)" to "Comments" on interface
"Name" to "Company name"
button "Add" to "Add new company"
"Upload" to "Upload new file"

**Comment by GiannisAnasta** [comment]
done

**Comment by GiannisAnasta** [comment]
russian localization isnt ready

**Comment by GiannisAnasta** [comment]
done
