### ISSUE TITLE
problem with enter in edit textarea

### ISSUE THREAD

**Issue by GiannisAnasta** [GiannisAnasta/Companies#25]
enter doesnt create a new line when its entered in edit textarea

**Comment by GiannisAnasta** [comment]
found the problem and when we fixed it we reopened another problem.
When selectionmode "multiple" was changed or not used at all our bug was fixed but when we returned the "multiple" selection the bug returned.
Current status: Im looking for a solution so we can keep the "multiple"selection, otherwise we have to make it by ourselfs :*(

**Comment by GiannisAnasta** [comment]
#12 duplicate

**Comment by jurasikasan** [comment]
нужно сделать кастомное выделение строк.
(нужно проанализировать и сохранить поведение как оно есть у феймворка)
кастомгое выделенеие должно исправить enter.
Если есть решение с сохранением выделения фреймворком - можно использоватьего, но мы не нашли

**Comment by GiannisAnasta** [comment]
done at last 
Git id : e24d7c4457e77a43be1ef302d336345bd32dc4e2
