### ISSUE TITLE
Bug with links

### ISSUE THREAD

**Issue by GiannisAnasta** [GiannisAnasta/Companies#3]
Not possible to open links which they dont start with the http:// form.

**Comment by jurasikasan** [comment]
original:

> > Кликабельные  сайты и емейлы.

normalize sites when it possible.
add http:// if it's absent or find better way
http://stackoverflow.com/questions/8951423/html-links-without-http-protocol
and use attribut  target="_blank" to open it in new tab

may be useful for validate a links
http://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/UrlValidator.html

**Comment by GiannisAnasta** [comment]
in progress

**Comment by GiannisAnasta** [comment]
done
