### ISSUE TITLE
Select all checkbox doesn't update header of table

### ISSUE THREAD

**Issue by jurasikasan** [GiannisAnasta/Companies#38]
Select all checkbox doesn't update header of table
steps to reproduce:
- select all
(should change "selected rows: " in header )

to check on done
- select all
- select all, deselect all
- select all, deselect one
- select one, select all
- select all, change page, select select all
- select all, change page, select one
...

**Comment by GiannisAnasta** [comment]
done.
ID(7ed0f0591e7e5d547adea03ab54b02a14b03f8d6)
