### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by GiannisAnasta** [GiannisAnasta/Companies#5]
Original comment >> Создайте русскую локализацию, пожалуйста.

Create Russian and English localization

**Comment by jurasikasan** [comment]
messages are not localized + new control (file parse type)

**Comment by jurasikasan** [comment]
- by default should be russian

**Comment by GiannisAnasta** [comment]
needed russian localization.

**Comment by GiannisAnasta** [comment]
done
