### ISSUE TITLE
Export / Import

### ISSUE THREAD

**Issue by GiannisAnasta** [GiannisAnasta/Companies#8]
Support different files for import / export like >> data_center_full.xlsx

**Comment by GiannisAnasta** [comment]
Support different files for import / export like >> data_center_full.xlsx

**Comment by jurasikasan** [comment]
export not done

**Comment by jurasikasan** [comment]
original:

> > Экспорт в новом формате.

implement export in new (one line with ';' separated lists) format

**Comment by GiannisAnasta** [comment]
done
